
create table to_do (
    id int8 generated by default as identity,
    created_date DATE, header varchar(255),
    description varchar(255), status varchar(255),
    user_id int8 REFERENCES users(id),
    primary key (id))